[project]
name = "mcp-server-weather"
version = "0.1.0"
description = "Example MCP Server integrated with Resonate to provide asynchronous tool calling capabilities."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.0",
    "resonate-sdk>=0.5.4",
]
