[project]
name = "mcp-server-weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.0",
    "resonate-sdk>=0.5.4",
]
